import os
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
import weather_engine

load_dotenv()

# Setup the Flask application
app = Flask(__name__)
# Secret key for session management and security
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "change-me")


@app.route("/")
def index():
    """Render the main landing page."""
    return render_template("index.html")


@app.route("/api/weather")
def get_weather():
    """
    Fetch weather data based on city name or geographic coordinates.
    Returns JSON data generated by the weather_engine.
    """
    city = request.args.get("city")
    lat_str = request.args.get("lat")
    lon_str = request.args.get("lon")

    # If a city name is provided, use it for fetching weather
    if city:
        return jsonify(weather_engine.get_weather_data(city_name=city.strip()))

    # If coordinates are provided, use them instead
    if lat_str and lon_str:
        try:
            return jsonify(weather_engine.get_weather_data(lat=float(lat_str), lon=float(lon_str)))
        except ValueError:
            # Handle invalid coordinate formats
            return jsonify({"error": "Invalid coordinates"}), 400

    # Default fallback to New Delhi if neither city nor coordinates are provided
    return jsonify(weather_engine.get_weather_data(city_name="New Delhi"))


@app.route("/health")
def health():
    """Health check endpoint for Render to monitor app status."""
    return jsonify({"status": "ok"})


if __name__ == "__main__":
    # Use the PORT environment variable if available, otherwise default to 5000
    port = int(os.environ.get("PORT", 5000))
    # Enable debug mode if running in development environment
    debug = os.environ.get("FLASK_ENV") == "development"
    app.run(debug=debug, host="0.0.0.0", port=port)
